# -*- coding: utf-8 -*-
"""Fatorial_Básico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QiumrWFeaIWeKe2ljvngFDrEzqJrRSvX
"""

#Esse código se baseia em um loop para calcular fatoriais de números inteiros, utilizando principalmente uma função, ele calcula um fatorial de cada vez e é encerrado caso o usuário digite um número negativo
import math 
def fatorial_n(numero):
  fatorial = math.factorial(numero)
  return fatorial
print(fatorial_n(numero))
while numero >=0:
  numero = int(input("Digite um número qualquer:"))
  fatorial_n(numero)
  print("O fatorial de {} é {}".format(numero,fatorial_n(numero)))
  if numero >=0:
    continue
  else:
    break